version: '3.3'
services:
  ark:
    image: dm0275/ark-server
    restart: always
    hostname: ark
    volumes:
      - $ARK_MODS:/home/arkuser/ark_server/ShooterGame/Content/Mods
      - $ARK_HOME:/home/arkuser/ark_server/ShooterGame/Saved/SavedArks
      # - $ARK_GAME_INI:/home/arkuser/ark_server/ShooterGame/Saved/Config/LinuxServer/Game.ini
      # - $ARK_USER_INI:/home/arkuser/ark_server/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini
    ports:
      - 27015:27015/udp
      - 7778:7778
      - 7778:7778/udp
      - 7777:7777
      - 7777:7777/udp
    environment:
      - JOIN_PASSWORD
      - ADMIN_PASSWORD
      - SERVER_MAP
      - SERVER_NAME
      - ARK_MOD_IDS
      - EXTRA_CMDS
      - EXTRA_FLAGS

volumes:
  saves: {}