name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build image
      run: make build
    - name: Push image
      env:
        DOCKER_USERNAME: ${{ secrets.dockerUsername }}
        DOCKER_TOKEN: ${{ secrets.dockerToken }}
      run: make push
